/**
 * create-pr.mjs
 * ─────────────
 * Given the JSON analysis from analyze-failure.mjs, this script:
 *   1. Creates a branch: autofix/<run-id>-<short-sha>
 *   2. Applies the patch (find-and-replace in the target file)
 *   3. Commits and pushes
 *   4. Opens a GitHub Pull Request
 *   5. Posts an @mention comment on the PR asking for /approve-fix or /reject-fix
 *   6. Optionally sends a Slack message if SLACK_BOT_TOKEN and SLACK_CHANNEL_ID are set
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { execSync } from "child_process";
import { parseArgs } from "util";

// ── CLI args ────────────────────────────────────────────────────────────────
const { values: args } = parseArgs({
  options: {
    analysis: { type: "string" },
    "run-id": { type: "string" },
    actor:    { type: "string" },
    sha:      { type: "string" },
    branch:   { type: "string" },
    repo:     { type: "string" },
  },
});

const analysis     = JSON.parse(readFileSync(args.analysis, "utf8"));
const runId        = args["run-id"];
const actor        = args.actor;
const sha          = args.sha;
const sourceBranch = args.branch;
const repo         = args.repo;

// ── Shell helpers ────────────────────────────────────────────────────────────
function sh(cmd, opts = {}) {
  console.log(`$ ${cmd.slice(0, 120)}${cmd.length > 120 ? "…" : ""}`);
  return execSync(cmd, {
    encoding: "utf8",
    stdio: opts.quiet ? "pipe" : "inherit",
    env: { ...process.env },
  });
}

// gh CLI wrapper — returns parsed JSON
function ghApi(endpoint, opts = {}) {
  const method = opts.method || "GET";
  const fields = opts.fields
    ? Object.entries(opts.fields).map(([k, v]) => `-f '${k}=${String(v).replace(/'/g, "'\\''")}'`).join(" ")
    : "";
  const result = sh(`gh api --method ${method} ${endpoint} ${fields}`, { quiet: true });
  try { return JSON.parse(result); } catch { return result; }
}

// ── Confidence badge ─────────────────────────────────────────────────────────
const confidenceBadge = { high: "🟢 High", medium: "🟡 Medium", low: "🔴 Low" }[analysis.confidence] ?? "⚪ Unknown";
const fixTypeLabel    = {
  code: "Code fix", config: "Config fix",
  dependency: "Dependency update", env: "Env / secret",
  trivy: "Security / Trivy", manual: "Manual steps",
}[analysis.fixType] ?? analysis.fixType;

// ══════════════════════════════════════════════════════════════════════════════
// 1 — Create the auto-fix branch
// ══════════════════════════════════════════════════════════════════════════════
const shortSha = sha.slice(0, 7);
const fixBranch = `autofix/${runId}-${shortSha}`;

console.log(`\n── Step 1: Creating branch ${fixBranch}`);
sh(`git config user.email "auto-healer[bot]@users.noreply.github.com"`);
sh(`git config user.name "Auto Healer"`);
sh(`git checkout ${sha}`);
sh(`git checkout -b ${fixBranch}`);

// ══════════════════════════════════════════════════════════════════════════════
// 2 — Apply the code patch (if Claude produced a code fix)
// ══════════════════════════════════════════════════════════════════════════════
let fixApplied = false;
let patchWarning = "";

const canPatch = (
  analysis.fixType !== "manual" &&
  analysis.fixType !== "env" &&
  analysis.fixType !== "trivy" &&
  analysis.fixFile !== null &&
  analysis.fixOriginal !== null &&
  analysis.fixReplacement !== null
);

if (canPatch) {
  console.log(`\n── Step 2: Applying patch to ${analysis.fixFile}`);

  if (!existsSync(analysis.fixFile)) {
    patchWarning = `⚠️ File \`${analysis.fixFile}\` not found in the repo — patch was skipped.`;
    console.warn(patchWarning);
  } else {
    const original = readFileSync(analysis.fixFile, "utf8");

    if (!original.includes(analysis.fixOriginal)) {
      patchWarning = `⚠️ The string Claude suggested patching was not found in \`${analysis.fixFile}\` — patch was skipped. This can happen when Claude's fixOriginal doesn't match the actual file content exactly.`;
      console.warn(patchWarning);
    } else {
      const patched = original.replace(analysis.fixOriginal, analysis.fixReplacement);
      writeFileSync(analysis.fixFile, patched, "utf8");

      sh(`git add "${analysis.fixFile}"`);
      sh(`git commit -m "fix: ${analysis.fixSummary}

Auto-generated by auto-healer for failed run #${runId}
Confidence: ${analysis.confidence}
Root cause: ${analysis.rootCause.slice(0, 200)}"`);

      fixApplied = true;
      console.log(`Patch applied and committed.`);
    }
  }
} else {
  console.log(`\n── Step 2: No code patch (fixType=${analysis.fixType}) — creating marker commit`);
  sh(`git commit --allow-empty -m "chore: auto-healer analysis for run #${runId} — ${fixTypeLabel}"`);
}

// ══════════════════════════════════════════════════════════════════════════════
// 3 — Push branch
// ══════════════════════════════════════════════════════════════════════════════
console.log(`\n── Step 3: Pushing ${fixBranch}`);
sh(`git push origin "${fixBranch}" --force-with-lease`);

// ══════════════════════════════════════════════════════════════════════════════
// 4 — Build PR description
// ══════════════════════════════════════════════════════════════════════════════
const manualSection = analysis.manualSteps?.length
  ? `\n## 🛠 Manual steps required\n\n${analysis.manualSteps.map((s, i) => `${i + 1}. ${s}`).join("\n")}\n`
  : "";

const patchWarningSection = patchWarning
  ? `\n> **⚠️ Patch warning:** ${patchWarning}\n`
  : "";

const prBody = `## 🤖 Auto-Healer Fix Proposal

> This PR was created automatically after the CI/CD pipeline failed.
> **Nothing is merged** until you explicitly reply \`/approve-fix\` or \`/reject-fix\` below.

---

| | |
|---|---|
| **Triggered by** | @${actor} |
| **Failed run** | [Run #${runId}](https://github.com/${repo}/actions/runs/${runId}) |
| **Failed step** | \`${analysis.failedStep}\` |
| **Fix type** | ${fixTypeLabel} |
| **Confidence** | ${confidenceBadge} |

---

## 🔍 Root cause

${analysis.rootCause}

## 💊 Fix

${fixApplied
  ? `**File patched:** \`${analysis.fixFile}\`\n\n${analysis.fixSummary}\n\nReview the diff in the **Files changed** tab above.`
  : `_No automatic code change was made — this is a **${fixTypeLabel}** issue._`
}
${patchWarningSection}
${manualSection}

${analysis.prBody}

---

## 👇 Your response

Reply to this PR with one of:

| Command | Effect |
|---|---|
| \`/approve-fix\` | Merge this PR (squash) and re-run the pipeline |
| \`/reject-fix\`  | Close this PR and handle it manually |

> ⚠️ Only @${actor} or repo admins can approve or reject.`;

// ══════════════════════════════════════════════════════════════════════════════
// 5 — Open the PR
// ══════════════════════════════════════════════════════════════════════════════
console.log(`\n── Step 4: Opening PR ${fixBranch} → ${sourceBranch}`);

// Escape the title and body for shell safety via a temp file
const tmpBodyFile = "/tmp/pr-body.md";
writeFileSync(tmpBodyFile, prBody, "utf8");

const prTitle = analysis.prTitle.replace(/"/g, '\\"');
let prUrl;
try {
  prUrl = sh(
    `gh pr create \
      --repo "${repo}" \
      --base "${sourceBranch}" \
      --head "${fixBranch}" \
      --title "${prTitle}" \
      --body-file "${tmpBodyFile}"`,
    { quiet: true }
  ).trim();
  console.log(`PR created: ${prUrl}`);
} catch (err) {
  console.error("Failed to open PR:", err.message);
  process.exit(1);
}

const prNumber = prUrl.split("/").pop();

// ══════════════════════════════════════════════════════════════════════════════
// 6 — Post the @mention comment
// ══════════════════════════════════════════════════════════════════════════════
console.log(`\n── Step 5: Notifying @${actor} on PR #${prNumber}`);

const comment = `Hey @${actor}! 👋 The pipeline broke on your last push and the auto-healer has a fix ready.

**❌ What went wrong** (${analysis.failedStep} step):
> ${analysis.rootCause}

**💊 Suggested fix** — ${confidenceBadge} confidence:
> ${analysis.fixSummary}

${fixApplied ? `A code change has been applied in this PR — please review the diff before approving.` : `This issue requires ${fixTypeLabel} — no automatic code change was made. See the PR body for steps.`}

---

Reply with \`/approve-fix\` to merge and redeploy, or \`/reject-fix\` to dismiss.`;

const tmpCommentFile = "/tmp/pr-comment.md";
writeFileSync(tmpCommentFile, comment, "utf8");

sh(
  `gh pr comment ${prNumber} --repo "${repo}" --body-file "${tmpCommentFile}"`,
  { quiet: true }
);

// ══════════════════════════════════════════════════════════════════════════════
// 7 — Slack notification (only if secrets are present)
// ══════════════════════════════════════════════════════════════════════════════
const slackToken   = process.env.SLACK_BOT_TOKEN;
const slackChannel = process.env.SLACK_CHANNEL_ID;

if (slackToken && slackChannel) {
  console.log(`\n── Step 6: Sending Slack notification`);
  try {
    const slackPayload = {
      channel: slackChannel,
      text: `🔧 Auto-Healer opened a fix PR for @${actor}'s failed pipeline`,
      blocks: [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*🔧 Auto-Healer Fix Ready*\n*Failed step:* \`${analysis.failedStep}\`   *Confidence:* ${confidenceBadge}`,
          },
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Root cause:*\n${analysis.rootCause.slice(0, 300)}`,
          },
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Fix:* ${analysis.fixSummary}\n*Triggered by:* @${actor}`,
          },
        },
        {
          type: "actions",
          elements: [
            {
              type: "button",
              text: { type: "plain_text", text: "Review PR" },
              url: prUrl,
              style: "primary",
            },
            {
              type: "button",
              text: { type: "plain_text", text: "View failed run" },
              url: `https://github.com/${repo}/actions/runs/${runId}`,
            },
          ],
        },
      ],
    };

    const response = await fetch("https://slack.com/api/chat.postMessage", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${slackToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(slackPayload),
    });

    const result = await response.json();
    if (result.ok) {
      console.log("Slack notification sent.");
    } else {
      console.warn("Slack API returned:", result.error);
    }
  } catch (err) {
    console.warn("Slack notification failed (non-fatal):", err.message);
  }
} else {
  console.log("Slack tokens not set — skipping Slack notification.");
}

console.log(`\n✅ Done! PR #${prNumber} created and @${actor} notified.`);
console.log(`PR: ${prUrl}`);
